apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ho-tro-bao-cao-tai-chinh
  description: Ứng dụng hỗ trợ lập BCTC
  annotations:
    github.com/project-slug: tin12b1/bctc
    backstage.io/techdocs-ref: dir:.
  tags:
    - python-2
    - react
spec:
  type: website
  lifecycle: development
  owner: group:default/kieu-hoi-tt-bien-mau
  providesApis:
    - report-api
  consumesApis:
    - login-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: login-api
  description: Dùng để đăng nhập hệ thống
spec:
  type: openapi
  lifecycle: development
  owner: group:default/kieu-hoi-tt-bien-mau
  definition: |
    openapi: "3.0.0"
    info:
      title: login-api
      version: "1.0.0"
      description: Dùng để đăng nhập hệ thống
    paths: {}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: report-api
  description: Hỗ trợ cung cấp các báo cáo liên quan BCTC
spec:
  type: openapi
  lifecycle: development
  owner: group:default/kieu-hoi-tt-bien-mau
  definition: |
    openapi: "2.0.0"
    info:
      title: report-api
      version: "1.0.0"
      description: Hỗ trợ cung cấp các báo cáo liên quan BCTC
    paths: {}
